[debian]
srv_debian01 ansible_host=172.16.191.144

[rocky]
srv_rocky01 ansible_host=172.16.191.145

[oracle]
srv_oracle01 ansible_host=172.16.191.148

[redhat:children]
rocky
oracle

[linux_servers:children]
debian
redhat
