---
base_common_packages:
  - vim
  - curl
  - wget
  - net-tools
  - python3

base_package_state: present

zabbix_server_ip: 172.16.191.144
zabbix_agent_package: zabbix-agent2
zabbix_agent_service: zabbix-agent2
zabbix_agent_port: 10050

zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_password: "{{ vault_zabbix_db_password }}"

grafana_package: grafana
grafana_service: grafana-server
grafana_port: 3000

zabbix_api_url: "http://172.16.191.144/zabbix/api_jsonrpc.php"
zabbix_api_user: Admin
zabbix_api_password: "{{ vault_zabbix_api_password }}"

zabbix_host_group_name: "Linux servers"
zabbix_template_name: "Linux by Zabbix agent"

zabbix_managed_hosts:
  - host: srv_debian01
    ip: 172.16.191.144
  - host: srv_rocky01
    ip: 172.16.191.145
  - host: srv_oracle01
    ip: 172.16.191.148