---
- name: Install base packages - RedHat-like servers
  hosts: redhat
  become: true
  gather_facts: false
  tags:
    - redhat
    - base-packages

  tasks:
    - name: Install EPEL repository
      ansible.builtin.dnf:
        name: "{{ epel_package }}"
        state: present
        update_cache: true
      tags:
        - epel
        - repositories

    - name: Install common and RedHat extra packages
      ansible.builtin.dnf:
        name: "{{ base_common_packages + redhat_extra_packages }}"
        state: "{{ base_package_state }}"
        update_cache: true
      tags:
        - packages
        - install


- name: Install base packages - Debian-like servers
  hosts: debian
  become: true
  gather_facts: false
  tags:
    - debian
    - base-packages

  tasks:
    - name: Install common and Debian extra packages
      ansible.builtin.apt:
        name: "{{ base_common_packages + debian_extra_packages }}"
        state: "{{ base_package_state }}"
        update_cache: true
      tags:
        - packages
        - install