---
- name: Install Zabbix Agent 2 on RedHat-like servers
  hosts: redhat
  become: true
  gather_facts: false

  tasks:
    - name: Install Zabbix official repository on RedHat-like servers
      ansible.builtin.dnf:
        name: "{{ zabbix_release_url }}"
        state: present
        disable_gpg_check: true
      tags:
        - zabbix-repo

    - name: Update DNF cache after adding Zabbix repository
      ansible.builtin.dnf:
        update_cache: true
      tags:
        - zabbix-repo

    - name: Install Zabbix Agent 2 on RedHat-like servers
      ansible.builtin.dnf:
        name: "{{ zabbix_agent_package }}"
        state: present
        update_cache: true
      tags:
        - zabbix-agent

    - name: Deploy Zabbix Agent 2 configuration
      ansible.builtin.template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart Zabbix Agent 2
      tags:
        - zabbix-config

    - name: Enable and start Zabbix Agent 2
      ansible.builtin.systemd_service:
        name: "{{ zabbix_agent_service }}"
        enabled: true
        state: started
      tags:
        - zabbix-service

    - name: Allow Zabbix Agent port on firewalld
      ansible.posix.firewalld:
        port: "{{ zabbix_agent_port }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      tags:
        - firewall
        - zabbix-agent

  handlers:
    - name: Restart Zabbix Agent 2
      ansible.builtin.systemd_service:
        name: "{{ zabbix_agent_service }}"
        state: restarted


- name: Install Zabbix Agent 2 on Debian-like servers
  hosts: debian
  become: true
  gather_facts: false

  tasks:
    - name: Install Zabbix Agent 2 on Debian-like servers
      ansible.builtin.apt:
        name: "{{ zabbix_agent_package }}"
        state: present
        update_cache: true
      tags:
        - zabbix-agent

    - name: Deploy Zabbix Agent 2 configuration
      ansible.builtin.template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: "0644"
        backup: true
      notify: Restart Zabbix Agent 2
      tags:
        - zabbix-config

    - name: Enable and start Zabbix Agent 2
      ansible.builtin.systemd_service:
        name: "{{ zabbix_agent_service }}"
        enabled: true
        state: started
      tags:
        - zabbix-service

  handlers:
    - name: Restart Zabbix Agent 2
      ansible.builtin.systemd_service:
        name: "{{ zabbix_agent_service }}"
        state: restarted