---
- name: Pre-check Connectivity
  hosts: linux_servers
  gather_facts: false

  tasks:
    - name: Check Connectivity
      ansible.builtin.ping:
      tags:
        - connectivity
        - always


- name: Update RedHat-like Linux Servers
  hosts: redhat
  become: true
  gather_facts: false

  tasks:
    - name: DNF | Update System
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      tags:
        - update


- name: Update Debian-like Linux Servers
  hosts: debian
  become: true
  gather_facts: false

  tasks:
    - name: APT | Update System
      ansible.builtin.apt:
        name: "*"
        state: latest
        update_cache: true
      tags:
        - update